# Average MLB pitch metrics (approximate values, 2023–2024 Statcast data)
# Includes precomputed Bauer Units (spin ÷ velocity)
# Expanded with release & movement data, plus uncommon pitches

PITCH_DATA = {
    "4_seam_fastball": {
        "avg_spin": 2250,
        "avg_velocity": 94,
        "avg_bauer_units": round(2250 / 94, 1),
        "avg_horizontal_break": 0.0,
        "avg_vertical_break": 8.0,
        "avg_release_height": 6.0,
        "avg_extension": 6.0,
    },
    "sinker": {
        "avg_spin": 2150,
        "avg_velocity": 93,
        "avg_bauer_units": round(2150 / 93, 1),
        "avg_horizontal_break": -3.0,
        "avg_vertical_break": 5.0,
        "avg_release_height": 5.9,
        "avg_extension": 6.0,
    },
    "slider": {
        "avg_spin": 2500,
        "avg_velocity": 85,
        "avg_bauer_units": round(2500 / 85, 1),
        "avg_horizontal_break": 7.0,
        "avg_vertical_break": -1.0,
        "avg_release_height": 5.9,
        "avg_extension": 6.1,
    },
    "changeup": {
        "avg_spin": 1800,
        "avg_velocity": 85,
        "avg_bauer_units": round(1800 / 85, 1),
        "avg_horizontal_break": -3.0,
        "avg_vertical_break": 3.0,
        "avg_release_height": 5.9,
        "avg_extension": 6.0,
    },
    "cutter": {
        "avg_spin": 2400,
        "avg_velocity": 89,
        "avg_bauer_units": round(2400 / 89, 1),
        "avg_horizontal_break": 4.0,
        "avg_vertical_break": 5.0,
        "avg_release_height": 6.0,
        "avg_extension": 6.0,
    },
    "split_finger_fastball": {
        "avg_spin": 2100,
        "avg_velocity": 84,
        "avg_bauer_units": round(2100 / 84, 1),
        "avg_horizontal_break": 0.0,
        "avg_vertical_break": -5.0,
        "avg_release_height": 5.9,
        "avg_extension": 6.0,
    },
    "two_seam_fastball": {
        "avg_spin": 2150,
        "avg_velocity": 92,
        "avg_bauer_units": round(2150 / 92, 1),
        "avg_horizontal_break": -4.0,
        "avg_vertical_break": 5.0,
        "avg_release_height": 6.0,
        "avg_extension": 6.0,
    },
    "curveball": {
        "avg_spin": 2600,
        "avg_velocity": 79,
        "avg_bauer_units": round(2600 / 79, 1),
        "avg_horizontal_break": 2.0,
        "avg_vertical_break": -6.0,
        "avg_release_height": 5.8,
        "avg_extension": 6.0,
    },
    # --- Additional / novelty pitches ---
    "sweeper": {  # horizontal breaking pitch, slower than slider
        "avg_spin": 2400,
        "avg_velocity": 83,
        "avg_bauer_units": round(2400 / 83, 1),
        "avg_horizontal_break": 9.0,
        "avg_vertical_break": -2.0,
        "avg_release_height": 5.9,
        "avg_extension": 6.0,
    },
    "knuckleball": {  # minimal spin, unpredictable movement
        "avg_spin": 600,
        "avg_velocity": 75,
        "avg_bauer_units": round(600 / 75, 1),
        "avg_horizontal_break": 4.0,  # highly variable
        "avg_vertical_break": 4.0,    # highly variable
        "avg_release_height": 5.9,
        "avg_extension": 6.0,
    },
    "eephus": {  # very slow, high arc
        "avg_spin": 1200,
        "avg_velocity": 55,
        "avg_bauer_units": round(1200 / 55, 1),
        "avg_horizontal_break": 1.0,
        "avg_vertical_break": 15.0,
        "avg_release_height": 5.9,
        "avg_extension": 6.0,
    },
    "gyroball": {  # unusual spin axis, mostly straight with drift
        "avg_spin": 2200,
        "avg_velocity": 88,
        "avg_bauer_units": round(2200 / 88, 1),
        "avg_horizontal_break": 1.0,
        "avg_vertical_break": 2.0,
        "avg_release_height": 5.9,
        "avg_extension": 6.0,
    },
}
